<div id="pnl_editpegawaipnddknoform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editpegawaipnddknoform-caption">{{STATE_BEG}}Riwayat Pendidikan Non Formal{{STATE_END}}</div>
		<a id="pnl_editpegawaipnddknoform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpegawaipnddknoform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editpegawaipnddknoform-form">

		<div class="form_row pnl_editpegawaipnddknoform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-txt_pegawaipnddkno_id" class="easyui-textbox" mapping="pegawaipnddkno_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaipnddknoform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Tempat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-txt_pegawaipnddkno_tempat" class="easyui-textbox" mapping="pegawaipnddkno_tempat"  maxlength="255"  style="width: 400px" data-options="prompt: 'Nama Tempat' , required: true, invalidMessage: 'Nama Tempat is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaipnddknoform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Kegiatan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-txt_pegawaipnddkno_kegiatan" class="easyui-textbox" mapping="pegawaipnddkno_kegiatan"  maxlength="255"  style="width: 400px" data-options="prompt: 'Nama Kegiatan' , required: true, invalidMessage: 'Nama Kegiatan is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaipnddknoform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kota</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-cbo_regency_id" class="easyui-combo" style="width: 400px" mapping="regency_id" display="name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Kota required', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editpegawaipnddknoform-cbo_regency_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaipnddknoform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tahun</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-txt_pegawaipnddkno_tahun" class="easyui-numberbox" mapping="pegawaipnddkno_tahun" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, invalidMessage: 'Tahun wajib diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row pnl_editpegawaipnddknoform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sertifikat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-fl_pegawaipnddkno_file" class="easyui-filebox" mapping="pegawaipnddkno_file" style="width: 400px" data-options="multiline: false  ">
				<div style="display: flex;">
					<a class="filedownloadlink" id="pnl_editpegawaipnddknoform-fl_pegawaipnddkno_file_link" style="cursor:pointer; margin-right: 10px; display: none">Download File</a>	
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
				<img id="pnl_editpegawaipnddknoform-fl_pegawaipnddkno_file_img" style="width: 200px; width: 200px; border: 1px solid: #ccc; display:none">				
			</div>
		</div>

		<div class="form_row pnl_editpegawaipnddknoform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Keterangan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-txt_pegawaipnddkno_descr" class="easyui-textbox" mapping="pegawaipnddkno_descr"  maxlength="10000"  style="width: 400px; height: 180px;" data-options="prompt: 'Keterangan' , required: true, invalidMessage: 'Keterangan is required', multiline: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaipnddknoform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Number ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaipnddknoform-txt_pegawai_id" class="easyui-textbox" mapping="pegawai_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'Number ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpegawaipnddknoform-autoadd" type="checkbox"><label for="pnl_editpegawaipnddknoform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpegawaipnddknoform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/pegawai-pegawaipnddknoform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editpegawaipnddknoform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editpegawaipnddknoform-buttonbar-left">
			<a id="pnl_editpegawaipnddknoform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editpegawaipnddknoform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editpegawaipnddknoform-buttonbar-middle">
			<a id="pnl_editpegawaipnddknoform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editpegawaipnddknoform-buttonbar-right">
			<a id="pnl_editpegawaipnddknoform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
