<div id="pnl_editpegawaikerjaform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editpegawaikerjaform-caption">{{STATE_BEG}}Riwayat Perkejaan{{STATE_END}}</div>
		<a id="pnl_editpegawaikerjaform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpegawaikerjaform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editpegawaikerjaform-form">

		<div class="form_row pnl_editpegawaikerjaform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_id" class="easyui-textbox" mapping="pegawaikerja_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Perusahaan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_nama" class="easyui-textbox" mapping="pegawaikerja_nama"  maxlength="255"  style="width: 400px" data-options="prompt: 'Perusahaan' , required: true, invalidMessage: 'Perusahaan is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tahun Masuk</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_thnmasuk" class="easyui-numberbox" mapping="pegawaikerja_thnmasuk" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, invalidMessage: 'Tahun Masuk wajib diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tahun Keluar</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_thnkeluar" class="easyui-numberbox" mapping="pegawaikerja_thnkeluar" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, invalidMessage: 'Tahun Keluar wajib diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Jabatan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_jabatan" class="easyui-textbox" mapping="pegawaikerja_jabatan"  maxlength="255"  style="width: 400px" data-options="prompt: 'Jabatan' , required: true, invalidMessage: 'Jabatan is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Keterangan Pekerjaan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_descr" class="easyui-textbox" mapping="pegawaikerja_descr"  maxlength="10000"  style="width: 400px; height: 180px;" data-options="prompt: 'Keterangan Pekerjaan' , required: true, invalidMessage: 'Keterangan Pekerjaan is required', multiline: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Alasan Keluar</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawaikerja_alasan" class="easyui-textbox" mapping="pegawaikerja_alasan"  maxlength="10000"  style="width: 400px; height: 180px;" data-options="prompt: 'Alasan Keluar' , required: true, invalidMessage: 'Alasan Keluar is required', multiline: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row pnl_editpegawaikerjaform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Paklaring</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-fl_pegawaikerja_file" class="easyui-filebox" mapping="pegawaikerja_file" style="width: 400px" data-options="multiline: false  ">
				<div style="display: flex;">
					<a class="filedownloadlink" id="pnl_editpegawaikerjaform-fl_pegawaikerja_file_link" style="cursor:pointer; margin-right: 10px; display: none">Download File</a>	
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
				<img id="pnl_editpegawaikerjaform-fl_pegawaikerja_file_img" style="width: 200px; width: 200px; border: 1px solid: #ccc; display:none">				
			</div>
		</div>

		<div class="form_row pnl_editpegawaikerjaform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Number ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikerjaform-txt_pegawai_id" class="easyui-textbox" mapping="pegawai_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'Number ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpegawaikerjaform-autoadd" type="checkbox"><label for="pnl_editpegawaikerjaform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpegawaikerjaform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/pegawai-pegawaikerjaform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editpegawaikerjaform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editpegawaikerjaform-buttonbar-left">
			<a id="pnl_editpegawaikerjaform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editpegawaikerjaform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editpegawaikerjaform-buttonbar-middle">
			<a id="pnl_editpegawaikerjaform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editpegawaikerjaform-buttonbar-right">
			<a id="pnl_editpegawaikerjaform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
