<div id="pnl_list">
	<div class="fgta-page-title">Daftar Pegawai</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<?php
		$customheadbutton = __DIR__.'/pegawai-list-customheadbutton.phtml'; 
		if (is_file($customheadbutton)) {
			include $customheadbutton;
		} else { ?>
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php } ?>

		<?php
		$customsearch = __DIR__.'/pegawai-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/pegawai-list-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>

			<thead>
				<tr>
					<th mapping="pegawai_id">pegawai_id</th>
					<th mapping="pegawai_nama">pegawai_nama</th>
					<th mapping="pegawai_email">pegawai_email</th>
					<th mapping="pegawai_hp">pegawai_hp</th>
					<th mapping="card_name">card_name</th>
					<th mapping="gender_name">gender_name</th>
					<th mapping="pegawai_iswna" type="checkbox">pegawai_iswna</th>
					<th mapping="marital_name">marital_name</th>
					<th mapping="pegawai_tgllahir">pegawai_tgllahir</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Number ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nama Lengkap</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Email</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Handphone</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Kartu Identitas</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Jenis Kelamin</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">isWna</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Status Perkawinan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tanggal</td>

				</tr>
			</thead>

			<?php } ?>

		</table>
	</div>


	<?php
	$customfootbutton = __DIR__.'/pegawai-list-customfootbutton.phtml'; 
	if (is_file($customfootbutton)) {
		include $customfootbutton;
	} 
	?>	

	<?php
	$custompagefooter = __DIR__.'/pegawai-list-custompagefooter.phtml'; 
	if (is_file($custompagefooter)) {
		include $custompagefooter;
	} 
	?>	

</div>