<div id="pnl_editpegawaialmtform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editpegawaialmtform-caption">{{STATE_BEG}}Alamat Sesuai Domisili{{STATE_END}}</div>
		<a id="pnl_editpegawaialmtform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpegawaialmtform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editpegawaialmtform-form">

		<div class="form_row pnl_editpegawaialmtform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-txt_pegawaialmt_id" class="easyui-textbox" mapping="pegawaialmt_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Provinsi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-cbo_province_id" class="easyui-combo" style="width: 400px" mapping="province_id" display="name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Provinsi required', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editpegawaialmtform-cbo_province_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kota</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-cbo_regency_id" class="easyui-combo" style="width: 400px" mapping="regency_id" display="name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Kota required', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editpegawaialmtform-cbo_regency_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kelurahan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-cbo_district_id" class="easyui-combo" style="width: 400px" mapping="district_id" display="name" data-options="editable:false, valueField:'id', textField:'text' , prompt: '-- PILIH --'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kecamatan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-cbo_villages_id" class="easyui-combo" style="width: 400px" mapping="villages_id" display="name" data-options="editable:false, valueField:'id', textField:'text' , prompt: '-- PILIH --'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kode POS</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-txt_pegawaialmt_kodepos" class="easyui-numberbox" mapping="pegawaialmt_kodepos" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Alamat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-txt_pegawaialmt_alamat" class="easyui-textbox" mapping="pegawaialmt_alamat"  maxlength="10000"  style="width: 400px; height: 180px;" data-options="prompt: 'Alamat' , required: true, invalidMessage: 'Alamat is required', multiline: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaialmtform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Number ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaialmtform-txt_pegawai_id" class="easyui-textbox" mapping="pegawai_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'Number ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpegawaialmtform-autoadd" type="checkbox"><label for="pnl_editpegawaialmtform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpegawaialmtform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/pegawai-pegawaialmtform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editpegawaialmtform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editpegawaialmtform-buttonbar-left">
			<a id="pnl_editpegawaialmtform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editpegawaialmtform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editpegawaialmtform-buttonbar-middle">
			<a id="pnl_editpegawaialmtform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editpegawaialmtform-buttonbar-right">
			<a id="pnl_editpegawaialmtform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
