<div id="pnl_editpegawaikelform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editpegawaikelform-caption">{{STATE_BEG}}Keluarga{{STATE_END}}</div>
		<a id="pnl_editpegawaikelform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpegawaikelform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editpegawaikelform-form">

		<div class="form_row pnl_editpegawaikelform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikelform-txt_pegawaikel_id" class="easyui-textbox" mapping="pegawaikel_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikelform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Hubungan Keluarga</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikelform-cbo_hubkel_id" class="easyui-combo" style="width: 400px" mapping="hubkel_id" display="hubkel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Hubungan Keluarga required', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editpegawaikelform-cbo_hubkel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikelform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikelform-txt_pegawaikel_nama" class="easyui-textbox" mapping="pegawaikel_nama"  maxlength="255"  style="width: 400px" data-options="prompt: 'Nama' , required: true, invalidMessage: 'Nama is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikelform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kota</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikelform-cbo_pegawaikel_tmptlahir" class="easyui-combo" style="width: 400px" mapping="pegawaikel_tmptlahir" display="name" data-options="editable:false, valueField:'id', textField:'text' , prompt: '-- PILIH --'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikelform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tanggal</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikelform-dt_pegawaikel_tgllahir" class="easyui-datebox" style="width: 400px" mapping="pegawaikel_tgllahir" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaikelform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Number ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaikelform-txt_pegawai_id" class="easyui-textbox" mapping="pegawai_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'Number ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpegawaikelform-autoadd" type="checkbox"><label for="pnl_editpegawaikelform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpegawaikelform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/pegawai-pegawaikelform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editpegawaikelform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editpegawaikelform-buttonbar-left">
			<a id="pnl_editpegawaikelform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editpegawaikelform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editpegawaikelform-buttonbar-middle">
			<a id="pnl_editpegawaikelform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editpegawaikelform-buttonbar-right">
			<a id="pnl_editpegawaikelform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
