<div id="pnl_editpegawaiorgform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editpegawaiorgform-caption">{{STATE_BEG}}Organisasi{{STATE_END}}</div>
		<a id="pnl_editpegawaiorgform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpegawaiorgform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editpegawaiorgform-form">

		<div class="form_row pnl_editpegawaiorgform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-txt_pegawaiorg_id" class="easyui-textbox" mapping="pegawaiorg_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaiorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-txt_pegawaiorg_nama" class="easyui-textbox" mapping="pegawaiorg_nama"  maxlength="255"  style="width: 400px" data-options="prompt: 'Nama' , required: true, invalidMessage: 'Nama is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaiorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sebagai</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-txt_pegawaiorg_sebagai" class="easyui-textbox" mapping="pegawaiorg_sebagai"  maxlength="255"  style="width: 400px" data-options="prompt: 'Sebagai' , required: true, invalidMessage: 'Sebagai is required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaiorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kota</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-cbo_regency_id" class="easyui-combo" style="width: 400px" mapping="regency_id" display="name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Kota required', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editpegawaiorgform-cbo_regency_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaiorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tahun</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-txt_pegawaiorg_tahun" class="easyui-numberbox" mapping="pegawaiorg_tahun" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, invalidMessage: 'Tahun wajib diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaiorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Keterangan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-txt_pegawaiorg_descr" class="easyui-textbox" mapping="pegawaiorg_descr"  maxlength="10000"  style="width: 400px; height: 180px;" data-options="prompt: 'Keterangan' , required: true, invalidMessage: 'Keterangan is required', multiline: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpegawaiorgform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Number ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpegawaiorgform-txt_pegawai_id" class="easyui-textbox" mapping="pegawai_id"  maxlength="36"  style="width: 400px" data-options="prompt: 'Number ID'  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpegawaiorgform-autoadd" type="checkbox"><label for="pnl_editpegawaiorgform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpegawaiorgform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/pegawai-pegawaiorgform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editpegawaiorgform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editpegawaiorgform-buttonbar-left">
			<a id="pnl_editpegawaiorgform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editpegawaiorgform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editpegawaiorgform-buttonbar-middle">
			<a id="pnl_editpegawaiorgform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editpegawaiorgform-buttonbar-right">
			<a id="pnl_editpegawaiorgform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
