<div id="pnl_list">
	<div class="fgta-page-title">Daftar Kontrak Pegawai</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<?php
		$customheadbutton = __DIR__.'/konpeg-list-customheadbutton.phtml'; 
		if (is_file($customheadbutton)) {
			include $customheadbutton;
		} else { ?>
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php } ?>

		<?php
		$customsearch = __DIR__.'/konpeg-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/konpeg-list-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>

			<thead>
				<tr>
					<th mapping="pegawai_nama">pegawai_nama</th>
					<th mapping="dept_name">dept_name</th>
					<th mapping="divisi_name">divisi_name</th>
					<th mapping="jabatan_nama">jabatan_nama</th>
					<th mapping="penempatan_nama">penempatan_nama</th>
					<th mapping="jenkonpeg_name">jenkonpeg_name</th>
					<th mapping="period_name">period_name</th>
					<th mapping="konpeg_isextend" type="checkbox">konpeg_isextend</th>
					<th mapping="konpeg_iswork" type="checkbox">konpeg_iswork</th>
					<th mapping="konpeg_workat">konpeg_workat</th>
					<th mapping="konpeg_workby">konpeg_workby</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Pegawai</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Divisi</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Jabatan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Penempatan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Jenis Kontrak</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Periode</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">isExtend</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">isWork</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Work Execute At</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Work Execute By</td>

				</tr>
			</thead>

			<?php } ?>

		</table>
	</div>


	<?php
	$customfootbutton = __DIR__.'/konpeg-list-customfootbutton.phtml'; 
	if (is_file($customfootbutton)) {
		include $customfootbutton;
	} 
	?>	

	<?php
	$custompagefooter = __DIR__.'/konpeg-list-custompagefooter.phtml'; 
	if (is_file($custompagefooter)) {
		include $custompagefooter;
	} 
	?>	

</div>